type Query{
    user:User,
    users:[User]
}


type Mutation{
    signup(username:String!, email:String!, password:String!, isAdmin:Boolean):Req
    signin(username:String!, email:String!, password:String!):Req
    updateuser(username:String, email:String, password:String):Req
    deletuser(user_id:ID):Req
}



type User{
    user_id:ID
    username:String
    email:String
    password:String
    isAdmin:Boolean
    ProductModels:[Product]
}


type Req{
    msg:String
    data:Any
}

scalar Any


 